<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Afutrans.Core\Afutrans.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Locales\" />
    <Folder Include="Documents\" />
    <Folder Include="Api\" />
  </ItemGroup>

</Project>
